micronaut:
  server:
    port: 8085
    cors:
      enabled: true
      allow-origin: "*"
      allow-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allow-headers: "Content-Type,Authorization,Origin,Accept"
      expose-headers: "Location"
      max-age: "1800"  
  application:
    name: sharedExpenses
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    entity-scan:
      packages:
        - 'com.nacho.expense.domain' 
        - 'com.nacho.expense.infraestructure' 
        - 'com.nacho.person.domain' 
        - 'com.nacho.person.infraestructure' 
    properties:
      hibernate:
        show-sql: true
        hbm2ddl:
          auto: update
        connection:
          db-type: postgres
